language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - pipenv run pytest # or py.test for Python versions 3.5 and below
  - pipenv run codecov
